from django.db import migrations, models
import uuid
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideBooking',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('pickup_address', models.CharField(max_length=512)),
                ('pickup_lat', models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)),
                ('pickup_lng', models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)),
                ('dropoff_address', models.CharField(max_length=512)),
                ('dropoff_lat', models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)),
                ('dropoff_lng', models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)),
                ('distance_km', models.DecimalField(max_digits=8, decimal_places=2)),
                ('num_adults', models.PositiveSmallIntegerField(default=1)),
                ('num_kids_seated', models.PositiveSmallIntegerField(default=0)),
                ('num_kids_carried', models.PositiveSmallIntegerField(default=0)),
                ('luggage_count', models.PositiveSmallIntegerField(default=0)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('payment_option', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16, default='PENDING')),
                ('price_breakdown', models.JSONField(null=True, blank=True)),
                ('total_amount', models.DecimalField(max_digits=10, decimal_places=2, default='0.00')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('method', models.CharField(max_length=32, blank=True)),
                ('amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('status', models.CharField(max_length=16, default='PENDING')),
                ('paynow_reference', models.CharField(max_length=128, null=True, blank=True)),
                ('paynow_response', models.JSONField(null=True, blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='payments', to='rides.ridebooking')),
            ],
        ),
    ]
# Generated by Django 6.0 on 2025-12-18 05:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_address', models.CharField(max_length=512)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_address', models.CharField(max_length=512)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_adults', models.PositiveSmallIntegerField(default=1)),
                ('num_kids_seated', models.PositiveSmallIntegerField(default=0)),
                ('num_kids_carried', models.PositiveSmallIntegerField(default=0)),
                ('luggage_count', models.PositiveSmallIntegerField(default=0)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('payment_option', models.CharField(choices=[('POA', 'Pay on Arrival'), ('PAYNOW', 'Pay Online (Paynow)')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('price_breakdown', models.JSONField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('paynow_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('paynow_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rides.ridebooking')),
            ],
        ),
    ]
