# Generated by Django 6.0 on 2026-08-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_alter_sitesettings_long_distance_extra_pax_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='hand_luggage_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hand_luggage_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Charge per hand luggage item beyond the free allowance. 0 = hand luggage always free.', max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hand_luggage_free',
            field=models.PositiveSmallIntegerField(default=1, help_text='Hand luggage items included free per booking.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_hand_luggage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum hand luggage items a customer may select. 0 = no limit.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_luggage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum luggage bags a customer may select. 0 = no limit.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_passengers',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum passengers a customer may select. 0 = no limit.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paynow_min_amount',
            field=models.DecimalField(decimal_places=2, default=201.0, help_text='Paynow is only offered when the fare is at or above this amount (Paynow fees are high on small amounts). 0 = always offer Paynow.', max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paynow_min_note',
            field=models.TextField(default='Paynow is only available for bookings of $201 and above. For $200 and below, please pay via Paylink or a money transfer agency (Western Union, Mukuru, WorldRemit, etc.).', help_text='Message shown to customers when their fare is below the Paynow minimum.'),
        ),
        migrations.AlterField(
            model_name='ridebooking',
            name='ride_type',
            field=models.CharField(choices=[('city', 'EasyTransit Ride'), ('long_distance', 'Long Distance'), ('chauffeur', 'Chauffeur Drive')], default='city', max_length=20),
        ),
    ]
