# Generated by Django 6.0 on 2026-08-27 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_ridebooking_hand_luggage_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='stops_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='night_end',
            field=models.TimeField(default=datetime.time(4, 0), help_text='End of the night window (e.g. 04:00). May cross midnight.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='night_start',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Start of the night window (e.g. 22:00).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='night_surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Flat amount added to the fare for pickups inside the night window.', max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='night_surcharge_enabled',
            field=models.BooleanField(default=True, help_text='Charge extra for pickups during the night window.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stop_tiers',
            field=models.JSONField(default=list, help_text='Charge bands for a stop along the way, per stop. Each entry needs max_minutes (int) and price (decimal); the first band whose max_minutes covers the stop is charged.'),
        ),
    ]
