# Generated by Django 6.0 on 2026-08-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_ridebooking_stops_json_sitesettings_night_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='is_return_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='return_trip_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage taken off the return leg when a customer books a round trip. 0 = the return leg costs the same as the outbound leg.', max_digits=5),
        ),
    ]
