# Generated by Django 6.0 on 2026-08-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_ridebooking_is_return_trip_ridebooking_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='cancelled_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='change_log',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_customer_cancellation',
            field=models.BooleanField(default=True, help_text='Let customers cancel their booking from the emailed link.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_customer_reschedule',
            field=models.BooleanField(default=True, help_text='Let customers change their pickup date and time from the emailed link.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_change_cutoff_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Customers can no longer change or cancel once the pickup is this many hours away. 0 = allowed right up to the pickup time.'),
        ),
    ]
