# Generated by Django 6.0 on 2026-08-30 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_ridebooking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='dropoff_point_detail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='flight_connection_details',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='flight_departure_airport',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='flight_details_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='flight_notes',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='pickup_airport_terminal',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='pickup_point_detail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance of the return leg when it runs a different route from the outbound trip.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_dropoff_address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_dropoff_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_dropoff_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_dropoff_point_detail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_pickup_address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_pickup_point_detail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='return_uses_different_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='airport_terminals',
            field=models.JSONField(default=list, help_text='Pickup points offered when a customer ticks "pickup is from an airport", as a list of labels, e.g. ["International Arrivals", "Domestic Arrivals"].'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_customer_flight_update',
            field=models.BooleanField(default=True, help_text='Let customers correct their flight details from the emailed link. Allowed right up to the pickup, since flights are often changed in transit.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hand_luggage_fee',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Charge per hand luggage item beyond the free allowance. 0 = hand luggage always free.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hand_luggage_free',
            field=models.PositiveSmallIntegerField(default=5, help_text='Hand luggage items included free per booking.'),
        ),
    ]
