# Generated by Django 6.0 on 2026-08-28 04:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('image', models.FileField(help_text='JPG, PNG, WEBP or GIF.', upload_to='gallery/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('album', models.CharField(blank=True, help_text='Optional grouping, e.g. "Victoria Falls trip". Photos with the same album show together.', max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers show first within an album.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Short teaser shown on the blog listing. Leave blank to use the opening of the post.', max_length=300)),
                ('body', models.TextField(help_text='The post itself. Blank lines start a new paragraph.')),
                ('cover_image', models.FileField(blank=True, help_text='Optional header image (JPG, PNG, WEBP or GIF).', null=True, upload_to='blog/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('is_published', models.BooleanField(default=True, help_text='Untick to keep this as a draft, hidden from the public site.')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
